main_menu:
  main_menu_message: "--- Integrated System Simulation ---"
  main_menu_options: "1. Tasks\n2. Connected components\n0. Exit"
tasks_menu:
  tasks_menu_message: "<<< Tasks Module >>>"
  tasks_menu_options: "1. New Task\n2. List tasks\n3. Complete Next Task\n4. Undo Previous Task\n0. Go Back"
  new_task_message: "--> New Task <--"
  new_task_options: "1. New Component\n2. Connect\n0. Go Back"
  new_task_description_prompt: "Enter Task's Description: "
  new_task_new_component_prompt: "Enter Component's ID to Create (String): "
  new_task_connect_first_component_prompt: "Enter First Component to Connect: "
  new_task_connect_second_component_prompt: "Enter Second Component to Connect: "
components_menu:
  components_menu_message: "<<< Components Module >>>" 
  components_menu_options: "1. New Component\n2. Visualize\n3. Union\n4. Check Conectivity\n0. Go Back"
  new_component_prompt: "New Component's ID (String): "
  union_prompt_message: "--> Union of 2 Elements <--"
  union_prompt_first: "Enter First Component: "
  union_prompt_second: "Enter Second Component: "
  check_connectivity_prompt_message: "--> Checking Connectivity of 2 Elements <--"
  check_connectivity_prompt_first: "Enter First Component: "
  check_connectivity_prompt_second: "Enter Second Component: "
other:
  choose: "Choose: "
  not_in_list: "The Option is Not in the List"
